### PR TITLE
Update API_HOST value and check status code OK in alfaview wrapper

### PR DESCRIPTION
**Pull request by muratbinerbay**
Updates `API_HOST` to https://apis.alfaview.com/json/v1
Checks for `CommonReplyStatusCode::OK` in ReplyInfo-StatusCode in addition to checking for null to catch errors

### CODE REVIEW

**Comment by annismckenzie** [comment]
:shipit:!

**Review by annismckenzie — APPROVED** [review]
🎉

**Comment by ksophocleous** [comment]
https://apis.alfaview.com/json/v1 is requesting credentials ("staging"). Is this expected?

**Comment by annismckenzie** [comment]
> https://apis.alfaview.com/json/v1 is requesting credentials ("staging"). Is this expected?

It is not. I'm fixing it.

**Comment by annismckenzie** [comment]
> https://apis.alfaview.com/json/v1 is requesting credentials ("staging"). Is this expected?

@muratbinerbay tested that the Moodle plugin – which uses this library – works correctly and it does. The thing you're seeing is because accessing that URL doesn't lead to a service and therefor triggers a fallback handler – we can fix that though.

**Comment by ksophocleous** [comment]
Thanks for the explanation!

**Pull request merged**
